// ============================================
// HIREINBOX GUARDRAILS & ETHICS
//
// Core principles enforced across the platform:
// - Respectful language
// - AI is assistive only (human decides)
// - No auto-outreach
// - No private data storage beyond necessary
// - POPIA-safe behavior
// - Automated candidate emails for transparency
// - Support access everywhere
//
// Tone: "Less noise. More hires."
// ============================================

// Site URL for absolute URLs in emails
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://hireinbox.co.za';

// Brand tone configuration
export const BRAND = {
  tagline: 'Less noise. More hires.',
  name: 'HireInbox',
  supportEmail: 'support@hireinbox.co.za',
  privacyUrl: `${SITE_URL}/privacy`,
  termsUrl: `${SITE_URL}/terms`,
} as const;

// Respectful language guidelines
export const LANGUAGE_GUIDELINES = {
  // Never use these terms
  prohibited: [
    'rejected', // Use 'not progressing' or 'not successful'
    'failed', // Use 'did not meet criteria'
    'unqualified', // Use 'does not match requirements'
    'bad', // Use 'area for improvement'
    'poor', // Use 'needs development'
  ],

  // Preferred alternatives
  preferred: {
    rejected: 'not successful',
    failed: 'did not meet criteria',
    unqualified: 'does not match requirements',
    bad: 'area for improvement',
    poor: 'needs development',
    reject: 'do not progress',
    fail: 'not meet',
  },

  // Tone principles
  principles: [
    'Always assume positive intent',
    'Focus on growth and potential',
    'Be specific, not judgmental',
    'Explain the "why" behind decisions',
    'Respect candidate time and effort',
  ],
} as const;

// AI assistant guidelines
export const AI_GUIDELINES = {
  role: 'AI is assistive only. Humans make final decisions.',

  mustDo: [
    'Provide evidence for all recommendations',
    'Show confidence levels for AI assessments',
    'Allow human override of all AI decisions',
    'Explain reasoning in plain language',
    'Flag uncertainty explicitly',
  ],

  mustNotDo: [
    'Make final hiring decisions automatically',
    'Send outreach without human approval',
    'Store data beyond retention policy',
    'Scrape private social media profiles',
    'Contact candidates directly',
  ],

  disclosures: {
    screening: 'This assessment was generated by AI and should be reviewed by a human.',
    matching: 'Match scores are AI-generated estimates based on available information.',
    talentMapping: 'Results are based on publicly available information only.',
  },
} as const;

// POPIA compliance configuration
export const POPIA_CONFIG = {
  // Data retention periods (in days)
  retention: {
    candidateData: 365, // 1 year
    cvFiles: 365,
    screeningResults: 365,
    auditLogs: 730, // 2 years for compliance
    deletedAccountData: 30, // Grace period before permanent deletion
  },

  // Required consents
  consents: {
    dataProcessing: {
      required: true,
      description: 'We process your data to provide CV screening services',
    },
    talentPool: {
      required: false,
      description: 'Allow vetted employers to discover your profile',
    },
    marketing: {
      required: false,
      description: 'Receive tips and job market insights',
    },
  },

  // Data subject rights
  rights: [
    'Access your data',
    'Correct inaccurate data',
    'Delete your data',
    'Object to processing',
    'Data portability',
    'Withdraw consent',
  ],

  // Information officer
  informationOfficer: {
    email: 'privacy@hireinbox.co.za',
    responseTime: '30 days',
  },
} as const;

// Automated email configuration
export const EMAIL_TEMPLATES = {
  // Pass 0: CV Received
  cvReceived: {
    subject: 'Thank you for your application',
    tone: 'Warm and professional',
    mustInclude: [
      'Acknowledgement of receipt',
      'Next steps timeline',
      'Contact for questions',
      'Data processing notice',
    ],
  },

  // Pass 2: Shortlisted
  shortlisted: {
    subject: 'Great news about your application',
    tone: 'Encouraging and clear',
    mustInclude: [
      'Clear next steps',
      'Timeline expectations',
      'Preparation tips (optional)',
      'Contact for questions',
    ],
  },

  // Pass 6: Not Successful
  notSuccessful: {
    subject: 'Update on your application',
    tone: 'Respectful and constructive',
    mustInclude: [
      'Clear but kind communication',
      'Thank them for their time',
      'Encourage future applications (if appropriate)',
      'Talent pool invitation (with consent)',
    ],
    mustNotInclude: [
      'Specific reasons for rejection (liability)',
      'Comparison to other candidates',
      'Negative language about qualifications',
    ],
  },

  // Pass 7: Talent Pool
  talentPool: {
    subject: 'Join our Talent Pool',
    tone: 'Inviting and transparent',
    mustInclude: [
      'Clear opt-in mechanism',
      'What happens to their data',
      'How employers access profiles',
      'How to opt-out anytime',
    ],
  },
} as const;

// Support configuration
export const SUPPORT_CONFIG = {
  // Support button must be visible on all screens
  buttonVisible: true,
  buttonPosition: 'bottom-right',

  channels: {
    email: 'support@hireinbox.co.za',
    whatsapp: '+27 XX XXX XXXX', // To be configured
    responseTime: '24 hours',
  },

  // Quick help topics
  helpTopics: [
    'How does AI screening work?',
    'How is my data protected?',
    'How do I delete my account?',
    'How do I contact an employer?',
    'How do I update my CV?',
  ],
} as const;

// Escape regex metacharacters to prevent ReDoS attacks
function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Content moderation for AI responses
export function sanitizeAIResponse(text: string): string {
  let sanitized = text;

  // Replace prohibited terms with preferred alternatives
  for (const [prohibited, preferred] of Object.entries(LANGUAGE_GUIDELINES.preferred)) {
    const escapedTerm = escapeRegExp(prohibited);
    const regex = new RegExp(`\\b${escapedTerm}\\b`, 'gi');
    sanitized = sanitized.replace(regex, preferred);
  }

  return sanitized;
}

// Check if consent is valid
export function hasValidConsent(
  consents: Record<string, boolean>,
  requiredConsent: keyof typeof POPIA_CONFIG.consents
): boolean {
  const config = POPIA_CONFIG.consents[requiredConsent];
  if (!config.required) return true;
  return consents[requiredConsent] === true;
}

// Generate POPIA-compliant data export
export function generateDataExportNotice(): string {
  return `
Your data export includes:
- Profile information
- CV documents
- Screening results
- Application history
- Consent records

This export is provided in accordance with POPIA Section 23.
For questions, contact: ${POPIA_CONFIG.informationOfficer.email}
  `.trim();
}

// Audit log entry type
export interface AuditLogEntry {
  timestamp: string;
  action: string;
  userId: string;
  details: Record<string, unknown>;
  ipAddress?: string;
}

// Create audit log entry
export function createAuditEntry(
  action: string,
  userId: string,
  details: Record<string, unknown>
): AuditLogEntry {
  return {
    timestamp: new Date().toISOString(),
    action,
    userId,
    details,
  };
}

// Disclosure text generator
export function getAIDisclosure(context: 'screening' | 'matching' | 'talentMapping'): string {
  return AI_GUIDELINES.disclosures[context];
}
